title: Neil Maniar
#logo: /assets
description:
  Senior Data Analyst
  MS in Applied Mathematics | BS in Economics |
  Snowflake | dbt | SQL | Power BI | Python |
  nmaniar9@gmail.com |
  <a href="https://www.linkedin.com/in/neil-maniar-25136b161/">Linkedin</a> |


  
theme: jekyll-theme-minimal

