title: Neil Maniar
#logo: /assets
description:
  Business analyst
  MS in Applied Mathematics | BS in Economics
  Excel | SQL | Tableau | Python
  markdown: kramdown
  nmaniar9@gmail.com
  markdown: kramdown
  <a href="https://www.linkedin.com/in/neil-maniar-25136b161/">Linkedin</a>

  
theme: jekyll-theme-minimal

