title: Neil Maniar
#logo: /assets
description:
  Business analyst
  MS in Applied Mathematics | BS in Economics |
  Excel | SQL | Tableau | Python |
  nmaniar9@gmail.com |
  <a href="https://www.linkedin.com/in/neil-maniar-25136b161/">Linkedin</a> |
  <a href="https://public.tableau.com/app/profile/neil.maniar/">Tableau Public</a>

  
theme: jekyll-theme-minimal

