title: Neil Maniar
#logo: /assets
description:
  Business analyst
  MS in Applied Mathematics | BS in Economics
  Excel | SQL | Tableau | Python
  
  nmaniar9@gmail.com
  [Linkedin](https://www.linkedin.com/in/neil-maniar-25136b161/)
  
theme: jekyll-theme-minimal

